### PR TITLE
feat: l10n - German translation

### PR DESCRIPTION
**Pull request by m1ga**
Not all strings but a start:

Screenshot_20230611_124732

* main view and buttons
* create a new app process

### CODE REVIEW

**Comment by ewanharris** [comment]
This is awesome to see @m1ga, is there anything I can do to help this along?

**Comment by m1ga** [comment]
Thanks!

It would be nice if you could merge it once you've look at the code - no release yet. Then we can improve the translation (add more strings) and other people can start other language files. We have a spanish version waiting already :)

This would get everyone at the same base level and we can just continue to work on the language files itself

**Comment by ewanharris** [comment]
@m1ga would you mind if I potentially change the structure of the `package.nls.json` file so that we can extract title and descriptions for commands? I think I should be able to adapt the existing readme generation script to generate this file directly from the package.json

**Comment by m1ga** [comment]
not at all! Feel free to change it. I can add my translation to it if you create a different PR.

**Comment by ewanharris** [comment]
I just pushed a commit that runs [this script](https://gist.github.com/ewanharris/d6021ab4e12a2518196a2ec7001f698f) and generates all valid strings and updated the existing German translations.

I'll look to see if I can add this to the repo as a build step to help reduce the friction in adding these (i.e. edit the package.json as normal, then run the script to generate).

This PR looks good to me from a quick test so I'm happy to merge if you are @m1ga!

**Review by ewanharris — APPROVED** [review]

**Comment by m1ga** [comment]
This is awesome! that helps to translate all other strings later on 👍 
Looking good! Many people want to help translate it into their language already 😄

**Pull request merged**
