### PR TITLE
[Axway Extension] Strip functionality and add walkthrough to migrate to TiDev extension

### PR DESCRIPTION
**Pull request by ewanharris**
This strips out all of the contributions from the extension that will conflict with the TiDev extension and adds a walkthrough (below) that will do the following:

1. Install the new extension
2. Export the settings to this new extension - Using the command added to the TiDev extension in [this commit](https://github.com/tidev/vscode-titanium/pull/980/commits/6abe6a949b7e77c4ac643b47dcc94aa7c1839ae4)
3. Allow exporting keystore data to the new extension - Using the command added to the TiDev extension in [this commit](https://github.com/tidev/vscode-titanium/pull/980/commits/6abe6a949b7e77c4ac643b47dcc94aa7c1839ae4)
4. Open the page to uninstall the old extension (we can't do this automatically)

image

On launch the Axway extension will show a warning message informing the user to migrate, when they click the `Migrate` button in that message it will open the walkthrough that will guide them through the steps. The walkthrough is a [VS Code feature](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs), it's there for this kind of functionality where you want to guide users through a process

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Is it worth updating all the GitHub references to point to https://github.com/tidev/vscode-titanium?

**Comment by cb1kenobi** [comment]
I suppose we don't care that the unit tests fail? :)

**Comment by cb1kenobi** [comment]
I have no idea what's going on in this PR. You delete basically every file. I get you're removing everything that conflicts with the TiDev version (which we haven't published, right?), but I have no idea how you're rendering that screen above. I'm totally lost here.

So, maybe we just hop on a call together and go through this. I'm super confused. As usual.

**Comment by ewanharris** [comment]
@cb1kenobi, for this PR I don't think we need to worry about making sure the GitHub refs are correct. I can do that for the PR to master though. Unit tests was an oversight, there's nothing really to test so I'll just make them pass.

Happy to jump on a call to go through this

**Comment by ewanharris** [comment]
To test this:

1. Checkout this branch
2. Build the extension using `npx vsce package`
3. Uninstall any other Titanium extension in VS Code, and then install the file created by step 2
4. Open VS Code and run through the workflow

**Pull request merged**
