### PR TITLE
feat: support building for macos

### LINKED ISSUE #1129: Adding build options for macos, macos-adhoc, MacAppStore
adding missing option to build for macos, macos-adhoc and MacAppStore

### PR DESCRIPTION
**Pull request by ewanharris**
Marking draft as this is a WIP, would like to test debugging and other items first but am struggling to be able to build to macOS on my machine 🤷🏻 

Closes #1129

### CODE REVIEW

**Comment by hansemannn** [comment]
@ewanharris I would actually take this for a base implementation already and then we could still iterate on it later. Would that be okay?

**Comment by ewanharris** [comment]
@hansemannn that sounds good to me, lemme check it out again later and get it merged

**Comment by ewanharris** [comment]
@hansemannn are you looking to use this? Want a release putting out?

**Comment by hansemannn** [comment]
I don't need it personally, but thought some users that have macOS apps could benefit from it :)

**Pull request merged**
